import turtle
import random
t = turtle.Turtle()
t.speed(0)
t.fillcolor("red")
t.begin_fill()
t.circle(random.randint(10, 200))
t.end_fill()
t.forward(random.randint(100, 150))
t.fillcolor("green")
t.begin_fill()
t.circle(random.randint(10, 200))
t.end_fill()
t.forward(random.randint(100, 150))
t.fillcolor("yellow")
t.begin_fill()
t.circle(random.randint(10, 200))
t.end_fill()
t.forward(random.randint(100, 150))
t.fillcolor("blue")
t.begin_fill()
t.circle(random.randint(10, 200))
t.end_fill()
turtle.done()