a = int(input())
b = int(input())
print("{0} - {1} = {2}".format(a, b, a- b))
print("{0} * {1} = {2}".format(a, b, a * b))
print("{0} / {1} = {2}".format(a, b, a / b))
print("{0} // {1} = {2}".format(a, b, a // b))
print("{0} % {1} = {2}".format(a, b, a % b))
