from random import *
import turtle
t = turtle.Turtle()
t.pendown()
t.shape('turtle')
t.write('0')
t.goto(150, 0)
t.write('150')
t.goto(300, 0)
t.color('sky blue')
t.begin_fill()
t.forward(75)
t.setheading(90)
t.forward(75)
t.setheading(180)
t.forward(75)
t.setheading(270)
t.forward(75)
t.end_fill()
t.penup()
t.goto(375, 75)
t.pendown()
t.color('blue')
t.begin_fill()
t.setheading(120)
t.forward(75)
t.setheading(240)
t.forward(75)
t.end_fill()
t.penup()
t.goto(300, 0)
t.write('400')
fruit = ["apple", "banana", "strawberry", "watermelon", "mandarin", "peach", "grapes", "orange", "pear", "kiwi"]
score = 0
n = randint(5, 10)
for i in range(n):
    s = choice(fruit)
    word = turtle.textinput("fruit", "%s(%d/%d)" % (s, i + 1, n))
    if s == word:
        score += 1
rate = score / n * 100
t.penup()
t.goto(0, -50)
t.write("%d/%d번 성공!" %(score, n), True, font = ("Arial", 15, "bold"))
t.penup()
t.goto(0, -100)
t.pendown()
t.write("정확도: %.1f%%" % (rate), True, font = ("Arial", 15, "bold"))
turtle.done()