import turtle
t = turtle.Turtle()
turtle.addshape("사람.gif")
t.shape("사람.gif")
t.stamp()
t.goto(100, 0)
t.stamp()
t.goto(100, 100)
t.stamp()
t.goto(0, 100)
t.stamp()
t.goto(0, 0)
turtle.done()
